version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
      target: prod
      context: .
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - static_volume:/usr/src/cellcounter-static/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev

#volumes:
#    static_volume:
