# CircleCI test config for cellcounter

version: 2.1

orbs:
  python: circleci/python@2.0.3
  node: circleci/node@5.0.2

jobs:
  test-server:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: "Install build dependencies"
          command: |
            ( sudo apt-get update || sudo apt-get update )
            sudo apt-get install libmemcached-dev
      - run:
          name: "Install python dependencies"
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r test-requirements.txt
      - run:
          name: "Migrate database"
          command: python manage.py migrate
      - run:
          name: "Run server tests"
          command: |
            export TEST=True
            python manage.py test
  test-integration:
    docker:
      - image: cimg/node:current
    environment:
      ALLOWED_HOSTS: "127.0.0.1"
      NODE_ENV: "development"
    steps:
      - checkout
      - run:
          name: "Install build dependencies"
          command: |
            ( sudo apt-get update || sudo apt-get update )
            sudo apt-get install libmemcached-dev python3-pip
      - python/install-packages:
          pkg-manager: pip
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Migrate database"
          command: python3 manage.py migrate
      - run:
          name: "Run integration tests"
          command: |
            echo 'export PATH=./node_modules/.bin:$PATH' >> $BASH_ENV
            ./test_integration.sh

workflows:
  test-workflow:
    jobs:
    - test-server
    - test-integration
