# Generated by Django 2.2.3 on 2019-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='celltype',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cellimage',
            name='file',
            field=models.ImageField(upload_to='cell_images'),
        ),
        migrations.AlterField(
            model_name='cellimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cell_thumbnails'),
        ),
    ]
