# Generated by Django 2.2.3 on 2019-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_display_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celltype',
            name='display_order',
            field=models.IntegerField(unique=True),
        ),
    ]
